# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('sevoflurane', models.IntegerField(blank=True, null=True)),
                ('isofluroane', models.IntegerField(blank=True, null=True)),
                ('desflurane', models.IntegerField(blank=True, null=True)),
                ('n2o', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
